var int[] x = int[] <> {
    ret int{1,2,3,4,5,6}
}

var int[] oldX = int[] <> { ret ^x }
var int[] nx = int[] <> { ret ^push with (int[] <> {ret ^oldX}, int <> {ret 7}) }



log with (int[] <> {ret ^nx}, string <> { ret "\n"})


log with (int <> { ret ^at with (int[] <> {ret ^nx}, int <> {ret 3})}, string <> { ret "\n"})

var int[] nx_1 = int[] <> { ret ^setAt with (int[] <> {ret ^nx}, int <> {ret 3}, int <> {ret 8}) }

log with (int[] <> {ret ^nx_1}, string <> { ret "\n"})